export const ACTION_TYPES = {
  JOIN: 'JOIN',
  RESUME: 'RESUME',
  START_GAME: 'START_GAME',
  ACTION: 'ACTION',
  PING: 'PING',
  PONG: 'PONG'
};

export const GAME_ACTIONS = {
  PLAY_CARD: 'PLAY_CARD',
  ATTACH_ENERGY: 'ATTACH_ENERGY',
  USE_ABILITY: 'USE_ABILITY',
  ATTACK: 'ATTACK',
  SELECT_TARGET: 'SELECT_TARGET',
  CONFIRM_SELECTION: 'CONFIRM_SELECTION',
  END_TURN: 'END_TURN'
};

export const VALID_GAME_ACTION_TYPES = new Set([
  'CALL',
  'STATE_SNAPSHOT',
  ...Object.values(GAME_ACTIONS)
]);

export const SERVER_EVENTS = {
  ERROR: 'ERROR',
  ROOM_JOINED: 'ROOM_JOINED',
  ROOM_READY: 'ROOM_READY',
  STATE_UPDATE: 'STATE_UPDATE',
  FULL_STATE: 'FULL_STATE',
  ACTION_REJECTED: 'ACTION_REJECTED',
  ACTION_BROADCAST: 'ACTION_BROADCAST',
  PROMPT: 'PROMPT',
  LOG: 'LOG'
};
